# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


import math


def fibonacci(x):
    phi = (1 + math.sqrt(5)) / 2
    psi = 1 - phi
    return (phi**x - psi**x) / (phi - psi)


sum = 0
f = 0
i = 0

while f <= 4000000:
    i = i + 3
    f = int(fibonacci(i))
    sum = sum + f

print(sum - f)
